export const lezingen = {
  1353: [],
  1355: [
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "",
      apostel: "",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 19,14-20,9",
      apostel: "Rö 1,1-15",
      lezing: "Nu 10,1-10",
      vervolg: "Jes 66,1-24",
      evangelie: "Mt 21,1-17",
    },
    {
      wet: "Dt 20,10-21,6",
      apostel: "Rö 1,16-25",
      lezing: "Dt 21,7-9",
      vervolg: "Jes 51,12-52,12",
      evangelie: "Mt 21,18-27",
    },
    {
      wet: "Dt 21,10-21",
      apostel: "Rö 1,26-2,11",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 21,22-22,7",
      apostel: "Rö 2,12-24",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 22,8-23,7",
      apostel: "Rö 2,25-3,20",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 23,8-24",
      apostel: "Rö 3,21-31",
      lezing: "",
      vervolg: "",
      evangelie: "Mt 21,28-46",
    },
    {
      wet: "Dt 23,25-24,4",
      apostel: "Rö 4,1-12",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 24,5-13",
      apostel: "Rö 4,13-5,5",
      lezing: "",
      vervolg: "",
      evangelie: "Mt 22,1-22",
    },
    {
      wet: "Dt 24,14-25,16",
      apostel: "Rö 5,6-17",
      lezing: "Dt 25,17-19",
      vervolg: "Jes 52,13-54,10",
      evangelie: "Mt 22,23-46",
    },
    {
      wet: "Dt 26,1-11",
      apostel: "Rö 5,18-6,11",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 26,12-15",
      apostel: "Rö 6,12-23",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 26,16-19",
      apostel: "Rö 7,1-13",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 27,1-10",
      apostel: "Rö 7,14-8,4",
      lezing: "",
      vervolg: "",
      evangelie: "Mt 23,1-22",
    },
    {
      wet: "Dt 27,11-28,6",
      apostel: "Rö 8,5-17",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 28,7-69",
      apostel: "Rö 8,18-37",
      lezing: "",
      vervolg: "",
      evangelie: "Mt 23,23-39",
    },
    {
      wet: "Dt 29,1-5",
      apostel: "Rö 8,38-9,13",
      lezing: "Dt 29,6-8",
      vervolg: "Jes 60,1-22",
      evangelie: "Mt 24,1-14",
    },
    {
      wet: "Dt 29,9-28",
      apostel: "Rö 9,14-29",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 30,1-6",
      apostel: "Rö 9,30-10,13",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 30,7-14",
      apostel: "Rö 10,14-11,6",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 30,15-31,6",
      apostel: "Rö 11,7-24",
      lezing: "",
      vervolg: "",
      evangelie: "Mt 24,15-28",
    },
    {
      wet: "Dt 31,7-13",
      apostel: "Rö 11,25-36",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Dt 31,14-19",
      apostel: "Rö 12,1-14",
      lezing: "",
      vervolg: "",
      evangelie: "Mt 24,29-42",
    },
    {
      wet: "Dt 31,20-27",
      apostel: "Rö 12,15-13,7",
      lezing: "Dt 31,28-30",
      vervolg: "Jes 61,1-63,9",
      evangelie: "Mt 24,43-51",
    },
    {
      wet: "Ge 21,1-4",
      apostel: "Rö 13,8-14,12",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Ge 21,5-8",
      apostel: "Rö 14,13-15,6",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Ge 21,9-12",
      apostel: "Rö 15,7-21",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Ge 21,13-17",
      apostel: "Rö 15,22-33",
      lezing: "",
      vervolg: "",
      evangelie: "Mt 25,1-13",
    },
    {
      wet: "Ge 21,18-21",
      apostel: "Rö 16,1-16",
      lezing: "",
      vervolg: "",
      evangelie: "",
    },
    {
      wet: "Ge 21,22-27",
      apostel: "Rö 16,17-27",
      lezing: "",
      vervolg: "",
      evangelie: "Mt 25,14-30",
    },

  ],
  1383: [],
  1385: [],
  2354: [],
  2384: [],
  4354: [],
  4355: [],
  4383: [],
  4385: [],
  6353: [],
  6355: [],
  6383: [],
  6385: [],
};
